export FLASK_APP=app
export SQLALCHEMY_TRACK_MODIFICATIONS=False
export SQLALCHEMY_ECHO=True 
export FLASK_ENV=development
export TEMPLATES_AUTO_RELOAD=True 
export FLASK_DEBUG=1
export DEBUG_TB_ENABLED=True
export DEBUG_TB_INTERCEPT_REDIRECTS=False 